packages:
  - "apps/*"

allowBuilds:
  esbuild: true
  sharp: false
  workerd: set this to true or false

minimumReleaseAgeExclude:
  - miniflare@5.20261006.1-alpha
  - wrangler@4.149.0
  - astro@7.3.8
